-- Run this manually in Supabase SQL Editor to apply enhanced content
-- This updates sample lessons to use the new enhanced markdown syntax

-- Update the "Welcome to CT" lesson with enhanced content blocks
UPDATE activities 
SET content = '{
  "markdown": "# Welcome to Computational Thinking\n\n:::concept{title=\"Why This Matters\"}\nImagine you''re the general manager of a luxury hotel. A guest complains that their room wasn''t ready on time, breakfast was cold, and the spa appointment was double-booked. How do you solve all these problems efficiently?\n\nThis is exactly what computational thinking teaches you: **a systematic way to break down complex problems into manageable pieces and solve them effectively.**\n:::\n\n> \"Computational thinking is a fundamental skill for everyone, not just for computer scientists.\" - Jeannette M. Wing, Columbia University\n\n---\n\n## What is Computational Thinking?\n\n:::definition\n**Computational thinking (CT)** is a problem-solving approach that uses concepts from computer science to tackle challenges in any field. It''s not about thinking like a computer—it''s about thinking in a way that even a computer could follow.\n:::\n\nThink of CT as a **mental toolkit**. Just like a chef has knives, pans, and techniques, computational thinkers have strategies for:\n- Breaking problems apart\n- Finding patterns\n- Focusing on what matters\n- Creating step-by-step solutions\n\n---\n\n## Real-World Analogy: Running a Hotel\n\n:::example{title=\"Decomposition in Action\"}\nImagine you need to plan the opening of a new hotel:\n\n| Main Task | Sub-Tasks |\n|-----------|----------|\n| **Hotel Opening** | Staffing, Marketing, Supplies, Training |\n\nYou naturally **decompose** the big task into smaller ones. That''s computational thinking!\n:::\n\n---\n\n## What You''ll Learn in This Course\n\n| Module | Topic | What You''ll Master |\n|--------|-------|--------------------|\n| 1-2 | CT Foundations | The four pillars of problem-solving |\n| 3 | Algorithms | Designing step-by-step solutions |\n| 4-6 | Python Basics | Variables, data types, decisions |\n| 7-9 | Data & Loops | Collections and repetition |\n| 10-12 | Functions & OOP | Reusable, organized code |\n| 13-15 | Debugging & Review | Writing robust code |\n\n---\n\n:::tip\n**Start simple** - Even experts break problems into tiny pieces. Write things down and look for patterns in every problem you encounter.\n:::\n\n---\n\n:::takeaways\n- Computational thinking is a systematic problem-solving approach\n- It works in ANY field, not just technology\n- Four pillars: Decomposition, Pattern Recognition, Abstraction, Algorithms\n- This course builds from concepts to Python programming\n:::\n\nReady to discover the four pillars? Let''s continue!"
}'::jsonb
WHERE slug = 'welcome-to-ct' AND type = 'lesson';

-- Confirm update
SELECT title, slug FROM activities WHERE slug = 'welcome-to-ct';

